print("###############################")
print("#                             #")
print("#  Muhammad Dzul Fathi Ahyan  #")
print("#        2410817210011        #")
print("#                             #")
print("###############################")