Nama    =(input("Nama                   :"))
Nim     =(input("Nim                    :"))
Kelas   =(input("Kelas paralel          :"))
Ttl     =(input("Tempat/Tangal Lahir    :"))
Alamat  =(input("Alamat                 :"))
Hobby   =(input("Hobby                  :"))
Hp      =(input("No. Hp                 :"))

print("Nama                   :"+Nama)
print("Nim                    :"+Nim)
print("Kelas Paralel          :"+Kelas)
print("Tempat/Tanggal Lahir   :"+Ttl)
print("Hobby                  :"+Hobby)
print("No. Hp                 :"+Hp)